name: delivery_system
description: "A multi-app delivery management system that can be white-labeled and deployed per client."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies required for the workspace
dependencies:
  flutter:
    sdk: flutter
  melos: ^3.2.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: any
  json_serializable: any

# This is a workspace configuration - each app will have its own Flutter configuration
flutter:
  uses-material-design: true